name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Klonowanie repozytorium
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Ustawienie środowiska z Java i Maven
      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'

      # 3. Instalacja zależności Maven
      - name: Install dependencies
        run: mvn install

      # 4. Uruchomienie aplikacji (dry run)
      - name: Dry run application
        run: mvn exec:java -Dexec.mainClass="org.example.Main"

      # 5. Wykonanie testów jednostkowych
      - name: Run unit tests
        run: mvn test

      # 6. Pakowanie aplikacji do formatu .jar
      - name: Package application as .jar
        run: mvn package

      # 7. Przesłanie pliku .jar jako artefakt do pobrania
      - name: Set up JDK 11
    uses: actions/setup-java@v2
    with:
    distribution: 'temurin'  # Dodajemy dystrybucję 'temurin' dla Javy
    java-version: '11'

