name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main  # Lub 'master', jeśli to główna gałąź

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # Wybieramy dystrybucję Javy
          java-version: '11'

      - name: Run Maven dry run
        run: mvn compile  # Uruchamia kompilację, by sprawdzić, czy kod działa poprawnie

      - name: Run unit tests
        run: mvn test  # Uruchamia testy jednostkowe

      - name: Package to .jar
        run: mvn package  # Pakowanie aplikacji do pliku JAR

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app.jar
          path: target/*.jar  # Ścieżka do zapisanego pliku JAR
