name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up JDK
        uses: actions/setup-java@v3  # Updated to v3
        with:
          distribution: 'temurin'  # or your preferred JDK distribution
          java-version: '22'       # or your project's Java version

      - name: Build with Maven
        run: mvn clean install
